
[connectsetting]
  authpassword = "passwd"
  authusername = "ANT"
  ip = "127.0.0.1"
  port = "8482"
  supportremote = false

[encryptionpolicy]
  disableencryption = false
  forceencryption = false
  prefernoencryption = true

[enginesetting]
  datadir = "download"
  defaultipblocklist = "http://john.bitsurge.net/public/biglist.p2p.gz"
  defaulttrackerlist = "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt"
  disableipv4 = false
  disableipv6 = false
  enabledefaulttrackers = true
  maxactivetorrents = 5
  maxestablishedconns = 100
  socksproxyurl = ""
  tmpdir = "tmp"
  torrentdbpath = "storm.db"
  usesocksproxy = false

[loggersetting]
  logginglevel = 5
  loggingoutput = "file"

[torrentconfig]
  bep20 = ""
  debug = false
  defaultstorage = ""
  dhtconfig = ""
  disablepex = false
  disabletcp = false
  disabletrackers = false
  disableutp = false
  downloadratelimit = ""
  extendedhandshakeclientversion = ""
  httpuseragent = ""
  ipblocklist = ""
  listenaddr = ""
  listenport = 0
  nodht = false
  noupload = false
  peerid = ""
  seed = false
  uploadratelimit = ""
